### ISSUE TITLE
Update Filter using new backend filter options

### ISSUE THREAD

**Issue by viviant100** [podaac/swodlr-ui#114]
Update SWODLR UI filtering page with new parameters that can be selectively enabled/disabled for additional filtering.

**Comment by jbyrne6** [comment]
### Speed difference test
1. Add the same granule to both the SIT (new) and UAT (old) environment on swodlr-ui
2. Apply all the filters for that single granule
3. Click apply

### Results
- SIT (new): **1.6 s** with 163 total entries
- UAT (old): **2.3 s** with 49 total entries

### Note
My SIT has many more generated granules in the my data page table than my UAT does. This slows down the performance for the filters that are not yet using the endpoint (Status, Raster Resolution, UTM Zone Adjust, MGRS Band Adjust). SIT will be even faster when all filter properties are able to be used with the endpoint.
