### ISSUE TITLE
Suggest available cycle/pass/scenes as user is inputing them

### ISSUE THREAD

**Issue by viviant100** [podaac/swodlr-ui#21]

**Comment by viviant100** [comment]
@joshgarde we'll discuss what additional api work needed to support this capability.

**Comment by frankinspace** [comment]
Based on the information provided from swot science team perhaps a simple first go would be to just show the constraints in text on the UI rather then an auto-suggest feature.

```
Cycle: Valid values 0 - 399
Pass: Valid values 1 - 584
Scene: Valid values 1 - 154

To enter a range of values, enter two numbers separated by a hyphen (e.g. 1-10)
```

**Comment by jbyrne6** [comment]
Ok got it, I can implement that into the UI as a first pass at this feature.

**Comment by viviant100** [comment]
will do after https://github.com/podaac/swodlr/issues/89 is complete

**Comment by frankinspace** [comment]
Closing for now as spatial search is a better end user solution. Can revisit suggestions at another time
