### ISSUE TITLE
Populate "About" Page

### ISSUE THREAD

**Issue by viviant100** [podaac/swodlr-ui#24]
Work with AppSci on the following:
- [x] Provide citation to data product and tools
- [x] Describe the tool and the science behind the product generation
- [x] Provide a description of use cases
- [x] Give credit to originators of the tool and provenance of the algorithm
- [x] Add FAQ
- [x] Link to EarthData forum dedicated to SWODLR
- [ ] Version history of the tool

**Comment by jbyrne6** [comment]
From Alex and the algorithm team regarding how they should be credited in the SWODLR application.

"I've talked with a few people on our end, and the conclusion was not to include specific credit, just a blanket statement that the output is generated by the same processor used to generate the standard science data product, developed by the SWOT ADT."
