### ISSUE TITLE
Develop pages to show currently selected raster products

### ISSUE THREAD

**Issue by viviant100** [podaac/swodlr-ui#4]
Page for showing currently selected raster products
    - “currently selected” = SDP that user wants to customize

**Comment by jbyrne6** [comment]
There is a granule table to show the granules added for the products to be customized. Everything added to the table will be generated into products.
![swodlr-ui-lock-for-generation](https://github.com/podaac/swodlr-ui/assets/25046593/b0bfde3c-b695-43ef-ba9c-13afa58123ee)
