### ISSUE TITLE
Develop user friendly search for general user

### ISSUE THREAD

**Issue by viviant100** [podaac/swodlr-ui#49]
Implement spatial search functionality using the CMR API

A/C: Demonstrate user can use spatial search via GUI

**Comment by jbyrne6** [comment]
### Feature list

- Add controls to top right of map to draw a polygon, edit polygon, and delete polygon. These are only available when in the scene selection step.
- Spatial search will be run on closing of a newly drawn polygon or when a polygon is edited.
- Add spatial search options to select the date range of the spatial search.
