### ISSUE TITLE
Implement BrowserRouter for request routing

### ISSUE THREAD

**Issue by frankinspace** [podaac/swodlr-ui#56]
Current implementation uses `HashRouter` for routing user requests. This is inefficient and prevents indexing by search engines. Ideally we would like to use `BrowserRouter` instead as discussed here https://stackoverflow.com/a/70059194.

This would required developing a cloudfront action to handle URL manipulation prior to sending the request to the application.

**Comment by jbyrne6** [comment]
Notes from rubber ducky meeting
- fix bug where product parameters are not being loaded from url state
- add cycle/pass/scene combos to url state
