### ISSUE TITLE
Implement Permission Check: CMR Search for Specific Collection ID

### ISSUE THREAD

**Issue by viviant100** [podaac/swodlr-ui#80]
When a user first logs in, SWODLR UI performs a simple CMR search for the specific collection ID as an initial permission check.

If the collection search returns nothing,  it indicates that the user doesn't have access to that collection

**Comment by davidcolemanjpl** [comment]
SWODLR UI: 1.0.0-rc.8
SWODLR API: 0.0.1-alpha48
SWODLR-SIT
Firefox v123.0 (64-bit)


Validated using an EDL 'dummyuser'
User must clear the browser cache prior to initiating / attempting login using the  EDL 'dummyuser'.

**_Test Complete_**
 

Current user indication message in SWODLR UI:

"The SWOT dataset is not public yet. Until then, some functionality of this site will be limited. You are not yet able to add scenes, configure scenes, or generate products."

![permissions message-swodlr-UI](https://github.com/podaac/swodlr-ui/assets/57456095/f2ffe7f5-59cc-426f-ab70-262f7bb01dd1)
