### ISSUE TITLE
Interactive Tutorial Bugs (Part 2)

### ISSUE THREAD

**Issue by viviant100** [podaac/swodlr-ui#92]
- [x] 1. (5/18) - wording could be better enhanced - (fix)
- [x] 2. (6/18) - NOTE: "Note: the area of the polygon you are editing will be re-searched when editing the shape is saved."
- [x] 3. (14/18) - wording could be better - (fix) "This is this table showing the scenes you can customize."
- [x] 4. (16/18)- "This page shows you the statuses of products being generated and that have finished generating." It also shows NEW and generated products that failed / ERROR
- [ ] 5. Suggest merging tutorial pages 16/18 and 17/18 - 'MyData' page
- [x] 6. (18/18) - "Last" s/b "Exit Tutorial"

related ticket: https://github.com/podaac/swodlr-ui/issues/83

**Comment by jbyrne6** [comment]
For step 5, I rewrote the step 17/18 to be more clear but I think we should keep that extra step to elaborate more on how the user can download their product. I think this is more clear than combining this step and the previous step.
